### ISSUE TITLE
Build Android Studio Error

### ISSUE THREAD

**Issue by ngochuu90** [ksvc/KSYLive_Android#16]
This is Error Log

```
11-12 22:25:56.314 10101-10101/com.ksyun.live.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.ksyun.live.demo, PID: 10101
                                                                     java.lang.UnsatisfiedLinkError: No implementation found for long com.ksyun.media.streamer.util.audio.KSYBgmPlayer._init() (tried Java_com_ksyun_media_streamer_util_audio_KSYBgmPlayer__1init and Java_com_ksyun_media_streamer_util_audio_KSYBgmPlayer__1init__)
                                                                         at com.ksyun.media.streamer.util.audio.KSYBgmPlayer._init(Native Method)
                                                                         at com.ksyun.media.streamer.util.audio.KSYBgmPlayer.<init>(KSYBgmPlayer.java:79)
                                                                         at com.ksyun.media.streamer.capture.AudioPlayerCapture.<init>(AudioPlayerCapture.java:24)
                                                                         at com.ksyun.media.streamer.kit.KSYStreamer.initModules(KSYStreamer.java:165)
                                                                         at com.ksyun.media.streamer.kit.KSYStreamer.<init>(KSYStreamer.java:104)
                                                                         at com.ksyun.media.streamer.demo.CameraActivity.onCreate(CameraActivity.java:177)
                                                                         at android.app.Activity.performCreate(Activity.java:5975)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by FirmianaRain** [comment]
KSYLiveDemo/libksylive/libs is a soft link. Put the 'libs' in the root directory of this repository to the project.
