### ISSUE TITLE
开始直播不到一秒出现卡死情况

### ISSUE THREAD

**Issue by weipeng321** [ksvc/KSYLive_Android#47]
问题描述：原本使用的sdk版本是2.2.7版本，没有出现该问题，更新到2.3.2开始出现开始直播不到一秒会卡死，测试官方demo在没有开始直播的情况下预览画面也会卡死，每次都会出现。

机型：坚果 型号YQ601

操作系统：Smartisan OS v3.2.6

Adnroid版本:5.1.1

**Comment by chriszeng87** [comment]
好的，我们先复现下

**Comment by ZhanRu** [comment]
华为P6和努比亚也出现这个问题，这是日志：
10-31 16:47:56.364 5041-5041/com.ksyun.live.demo I/ViewRootImpl: CPU Rendering VSync enable = true
10-31 16:48:02.712 5041-5060/com.ksyun.live.demo W/art: Suspending all threads took: 10.338ms
10-31 16:48:02.729 5041-5067/com.ksyun.live.demo I/art: Background partial concurrent mark sweep GC freed 2670(208KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 6MB/10MB, paused 6.920ms total 55.606ms
10-31 16:48:03.381 5041-5041/com.ksyun.live.demo W/linker: /data/app/com.ksyun.live.demo-1/lib/arm64/libksylive.so: unused DT entry: type 0x6ffffffe arg 0x93110
10-31 16:48:03.382 5041-5041/com.ksyun.live.demo W/linker: /data/app/com.ksyun.live.demo-1/lib/arm64/libksylive.so: unused DT entry: type 0x6fffffff arg 0x3
10-31 16:48:03.410 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'java.nio.Buffer' loaded
10-31 16:48:03.410 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'java.nio.ByteBuffer' loaded
10-31 16:48:03.410 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'java.util.ArrayList' loaded
10-31 16:48:03.410 5041-5041/com.ksyun.live.demo I/J4A: API-Level: 22
10-31 16:48:03.411 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'android.media.AudioTrack' loaded
10-31 16:48:03.411 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
10-31 16:48:03.411 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'android.media.MediaCodec' loaded
10-31 16:48:03.411 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'android.media.MediaFormat' loaded
10-31 16:48:03.411 5041-5041/com.ksyun.live.demo W/J4A: J4ALoader: Ignore: 'android.media.PlaybackParams' need API 22
10-31 16:48:03.411 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'android.os.Bundle' loaded
10-31 16:48:03.412 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'com.ksyun.media.player.misc.IMediaDataSource' loaded
10-31 16:48:03.413 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'com.ksyun.media.player.KSYMediaPlayer' loaded
10-31 16:48:03.413 5041-5041/com.ksyun.live.demo D/J4A: J4ALoader: OK: 'com.ksyun.media.player.util.AudioUtil' loaded
10-31 16:48:03.420 5041-5041/com.ksyun.live.demo I/StatsLogReport: the log client is not been init or disable logreport
10-31 16:48:03.421 5041-5041/com.ksyun.live.demo I/BaseDemoFragment: deviceInfo:NX511J(model)_5.1.1(osver)_(band)_0(encode_h264)0(encode_h265)
10-31 16:48:03.421 5041-5771/com.ksyun.live.demo I/StatsLogReport: init log client begin
10-31 16:48:03.431 5041-5771/com.ksyun.live.demo D/StatsLogReport: get interval from local sharepreference : 30000
10-31 16:48:03.431 5041-5771/com.ksyun.live.demo I/StatsLogReport: init log cleint end
10-31 16:48:03.452 5041-5041/com.ksyun.live.demo I/Timeline: Timeline: Activity_launch_request id:com.ksyun.live.demo time:294585986
10-31 16:48:03.592 5041-5041/com.ksyun.live.demo W/linker: /data/app/com.ksyun.live.demo-1/lib/arm64/libksyapm.so: unused DT entry: type 0x6ffffffe arg 0x1dc88
10-31 16:48:03.592 5041-5041/com.ksyun.live.demo W/linker: /data/app/com.ksyun.live.demo-1/lib/arm64/libksyapm.so: unused DT entry: type 0x6fffffff arg 0x3
10-31 16:48:03.595 5041-5041/com.ksyun.live.demo W/J4A: J4ALoader: Ignore: 'android.media.PlaybackParams' need API 22
10-31 16:48:03.649 5041-5784/com.ksyun.live.demo D/Egl10Core: EGLContext created, client version 2
10-31 16:48:03.652 5041-5784/com.ksyun.live.demo D/FboManager: init
10-31 16:48:03.653 5041-5784/com.ksyun.live.demo D/CameraCapture: onGLContext ready
10-31 16:48:03.681 5041-5784/com.ksyun.live.demo D/CameraCapture: onSizeChanged 1x1
10-31 16:48:03.806 5041-5041/com.ksyun.live.demo D/KSYStreamer: onResume
10-31 16:48:03.808 5041-5784/com.ksyun.live.demo D/GlUtil: New Texture 2
10-31 16:48:03.811 5041-5041/com.ksyun.live.demo I/ViewRootImpl: CPU Rendering VSync enable = true
10-31 16:48:03.825 5041-5041/com.ksyun.live.demo I/nubialog: DispatchMessage in MainLooper, delay:322ms msg:{ when=-340ms what=100 obj=ActivityRecord{1cf5be67 token=android.os.BinderProxy@19a35226 {com.ksyun.live.demo/com.ksyun.media.streamer.demo.BaseCameraActivity}} target=android.app.ActivityThread$H }
10-31 16:48:03.914 5041-5785/com.ksyun.live.demo D/FboManager: init
10-31 16:48:03.915 5041-5785/com.ksyun.live.demo D/ImgTexPreview: onReady
10-31 16:48:03.915 5041-5785/com.ksyun.live.demo D/ImgTexPreview: onSizeChanged 1080x1920
10-31 16:48:03.916 5041-5785/com.ksyun.live.demo D/CameraCapture: start
10-31 16:48:03.922 5041-5802/com.ksyun.live.demo E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/test.png: open failed: ENOENT (No such file or directory)
10-31 16:48:03.922 5041-5802/com.ksyun.live.demo E/BitmapLoader: loadBitmap file:///storage/emulated/0/test.png failed!
10-31 16:48:03.940 5041-5778/com.ksyun.live.demo V/CameraHolder: open camera 1
10-31 16:48:04.117 5041-5041/com.ksyun.live.demo I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@19a35226 time:294586651
10-31 16:48:04.145 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 1920x1080
10-31 16:48:04.145 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 1440x1080
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 1280x960
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 1280x720
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 1080x1080
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 960x720
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 864x480
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 800x480
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 768x432
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 720x480
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 640x480
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 480x640
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 576x432
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 480x320
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 384x288
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 352x288
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 320x240
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 240x320
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 240x160
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 176x144
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 160x120
10-31 16:48:04.146 5041-5778/com.ksyun.live.demo D/CameraUtil: ==== Camera Support: 144x176
10-31 16:48:04.152 5041-5778/com.ksyun.live.demo D/CameraUtil: 10000-30000
10-31 16:48:04.159 5041-5778/com.ksyun.live.demo D/CameraCapture: try to preview with: 1280x720 15.0fps
10-31 16:48:04.184 5041-5778/com.ksyun.live.demo D/CameraCapture: Preview with: 
                                                                  1280x720 15.0-15.0fps
                                                                  FocusMode: fixed
                                                                  VideoStabilization: false
                                                                  Antibanding: auto
10-31 16:48:04.392 5041-5041/com.ksyun.live.demo D/CameraCapture: Camera preview started
10-31 16:48:04.392 5041-5041/com.ksyun.live.demo D/KSYStreamer: CameraCapture ready
10-31 16:48:04.392 5041-5041/com.ksyun.live.demo D/BaseCameraActivity: OnInfo: 1000 msg1: 0 msg2: 0
10-31 16:48:04.392 5041-5041/com.ksyun.live.demo D/BaseCameraActivity: KSY_STREAMER_CAMERA_INIT_DONE
10-31 16:48:04.393 5041-5041/com.ksyun.live.demo D/BaseCameraActivity: OnInfo: 1002 msg1: 1 msg2: 0
10-31 16:48:04.393 5041-5041/com.ksyun.live.demo D/BaseCameraActivity: KSY_STREAMER_CAMERA_FACING_CHANGED
10-31 16:48:04.449 5041-5784/com.ksyun.live.demo D/FboManager: Create and lock a new fbo: 3 360x640 total:1
10-31 16:48:04.470 5041-5784/com.ksyun.live.demo D/FboManager: Create and lock a new fbo: 4 360x640 total:2
10-31 16:48:04.505 5041-5784/com.ksyun.live.demo D/GlUtil: New Texture 5
10-31 16:48:04.520 5041-5784/com.ksyun.live.demo D/GlUtil: New Texture 6
10-31 16:48:04.529 5041-5784/com.ksyun.live.demo D/FboManager: Create and lock a new fbo: 7 360x640 total:3
10-31 16:48:06.715 5041-5789/com.ksyun.live.demo W/System.err: java.net.SocketTimeoutException: failed to connect to /183.131.29.12 (port 80) after 3000ms
10-31 16:48:06.716 5041-5789/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at java.net.Socket.connect(Socket.java:882)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:152)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
10-31 16:48:06.717 5041-5789/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
10-31 16:48:06.718 5041-5789/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
10-31 16:48:06.718 5041-5789/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:496)
10-31 16:48:06.718 5041-5789/com.ksyun.live.demo W/System.err:     at com.ksyun.media.streamer.util.https.KsyHttpConnection$1.run(KsyHttpConnection.java:125)
10-31 16:48:06.718 5041-5789/com.ksyun.live.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-31 16:48:06.719 5041-5789/com.ksyun.live.demo D/KsyHttpClient: http response code: -1 response message : null
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo E/DeviceInfoTools: Send request failed
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err: java.net.SocketTimeoutException: failed to connect to devinfo.ks-live.com/120.92.8.220 (port 8420) after 5000ms
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at java.net.Socket.connect(Socket.java:882)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:152)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
10-31 16:48:08.409 5041-5073/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at com.ksyun.media.streamer.util.device.DeviceInfoTools$a.a(DeviceInfoTools.java:230)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at com.ksyun.media.streamer.util.device.DeviceInfoTools$a.doInBackground(DeviceInfoTools.java:204)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-31 16:48:08.410 5041-5073/com.ksyun.live.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-31 16:48:11.737 5041-5786/com.ksyun.live.demo E/TimeDeltaUtil: doRetry:1
10-31 16:48:14.746 5041-6084/com.ksyun.live.demo W/System.err: java.net.SocketTimeoutException: failed to connect to /183.131.29.12 (port 80) after 3000ms
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at java.net.Socket.connect(Socket.java:882)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:152)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
10-31 16:48:14.747 5041-6084/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
10-31 16:48:14.748 5041-6084/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:496)
10-31 16:48:14.748 5041-6084/com.ksyun.live.demo W/System.err:     at com.ksyun.media.streamer.util.https.KsyHttpConnection$1.run(KsyHttpConnection.java:125)
10-31 16:48:14.748 5041-6084/com.ksyun.live.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-31 16:48:14.748 5041-6084/com.ksyun.live.demo D/KsyHttpClient: http response code: -1 response message : null
10-31 16:48:19.775 5041-5786/com.ksyun.live.demo E/TimeDeltaUtil: doRetry:2
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err: java.net.SocketTimeoutException: failed to connect to /183.131.29.12 (port 80) after 3000ms
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at java.net.Socket.connect(Socket.java:882)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:152)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:496)
10-31 16:48:22.792 5041-6288/com.ksyun.live.demo W/System.err:     at com.ksyun.media.streamer.util.https.KsyHttpConnection$1.run(KsyHttpConnection.java:125)
10-31 16:48:22.793 5041-6288/com.ksyun.live.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-31 16:48:22.793 5041-6288/com.ksyun.live.demo D/KsyHttpClient: http response code: -1 response message : null
10-31 16:48:22.793 5041-5786/com.ksyun.live.demo E/TimeDeltaUtil: quit
10-31 16:49:03.457 5041-5772/com.ksyun.live.demo D/auth: Signature = DBueByFszIxu/m2U6Zf1yJIYVpU=
10-31 16:49:05.831 5041-5060/com.ksyun.live.demo W/art: Suspending all threads took: 12.260ms
10-31 16:49:05.851 5041-5067/com.ksyun.live.demo I/art: Background sticky concurrent mark sweep GC freed 13410(1387KB) AllocSpace objects, 5(80KB) LOS objects, 8% free, 17MB/18MB, paused 8.105ms total 36.108ms
10-31 16:49:23.483 5041-5772/com.ksyun.live.demo W/System.err: java.net.UnknownHostException: Unable to resolve host "videodev.ksyun.com": No address associated with hostname
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
10-31 16:49:23.484 5041-5772/com.ksyun.live.demo W/System.err:     at com.ksy.statlibrary.log.LogClient.sendRecordJson(LogClient.java:200)
10-31 16:49:23.485 5041-5772/com.ksyun.live.demo W/System.err:     at com.ksy.statlibrary.log.LogClient.sendRecord(LogClient.java:320)
10-31 16:49:23.485 5041-5772/com.ksyun.live.demo W/System.err:     at com.ksy.statlibrary.log.LogClient.access$300(LogClient.java:41)
10-31 16:49:23.485 5041-5772/com.ksyun.live.demo W/System.err:     at com.ksy.statlibrary.log.LogClient$1.run(LogClient.java:293)
10-31 16:49:23.485 5041-5772/com.ksyun.live.demo W/System.err:     at java.util.Timer$TimerImpl.run(Timer.java:284)
10-31 16:49:23.485 5041-5772/com.ksyun.live.demo W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
10-31 16:49:23.490 5041-5772/com.ksyun.live.demo W/System.err:     at libcore.io.Posix.android_getaddrinfo(Native Method)
10-31 16:49:23.490 5041-5772/com.ksyun.live.demo W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
10-31 16:49:23.491 5041-5772/com.ksyun.live.demo W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
10-31 16:49:23.491 5041-5772/com.ksyun.live.demo W/System.err: 	... 14 more
