### ISSUE TITLE
开播偶现崩溃

### ISSUE THREAD

**Issue by Mr-wangyong** [ksvc/KSYLive_Android#66]
手机型号： oppo x9007
android版本：4.4.4
FATAL EXCEPTION: EncodeThread
                                                   Process: com.blinnnk.thor, PID: 14422
                                                   java.lang.UnsatisfiedLinkError: Native method not found: com.ksyun.media.streamer.encoder.AVEncoderWrapper._open_video:(JIIIIIFFIIIZ)I
                                                       at com.ksyun.media.streamer.encoder.AVEncoderWrapper._open_video(Native Method)
                                                       at com.ksyun.media.streamer.encoder.AVEncoderWrapper.a(AVEncoderWrapper.java:54)
                                                       at com.ksyun.media.streamer.encoder.AVCodecVideoEncoder.a(AVCodecVideoEncoder.java:35)
                                                       at com.ksyun.media.streamer.encoder.Encoder$4.handleMessage(Encoder.java:503)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by chriszeng87** [comment]
麻烦用最新的版本试一下？
